/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "pdlukbnekyrygnzvhetg";
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBkbHVrYm5la3lyeWduenZoZXRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2NzU5NzAsImV4cCI6MjA3MTI1MTk3MH0.5e7E7YuBM098T_4iazSWfV7IpQ6X1iQBTIrBlR52cAY";